# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('mileage', models.IntegerField(verbose_name='\u041f\u0440\u043e\u0431\u0435\u0433')),
            ],
            options={
                'verbose_name': '\u041c\u0430\u0448\u0438\u043d\u0430',
                'verbose_name_plural': '\u041c\u0430\u0448\u0438\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('mileage', models.IntegerField(verbose_name='\u041f\u0440\u043e\u0431\u0435\u0433')),
            ],
            options={
                'verbose_name': '\u0414\u0435\u0442\u0430\u043b\u044c',
                'verbose_name_plural': '\u0414\u0435\u0442\u0430\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u041c\u043e\u0434\u0435\u043b\u044c',
                'verbose_name_plural': '\u041c\u043e\u0434\u0435\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0414\u0435\u0442\u0430\u043b\u044c',
                'verbose_name_plural': '\u0414\u0435\u0442\u0430\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='OfficialDealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0414\u0438\u043b\u0435\u0440',
                'verbose_name_plural': '\u0414\u0438\u043b\u0435\u0440\u044b',
            },
        ),
    ]
