# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='journal.CarModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardetail',
            name='car',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='journal.Car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='dealer',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='journal.OfficialDealer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='details',
            field=models.ManyToManyField(blank=True, to='journal.Detail'),
        ),
    ]
