# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20160612_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetail',
            name='nomenclature',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='journal.Detail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.CarModel'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Car'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.OfficialDealer'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='details',
            field=models.ManyToManyField(related_name='maps', to='journal.Detail'),
        ),
    ]
