# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20160612_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.CarModel', verbose_name='\u041c\u043e\u0434\u0435\u043b\u044c \u043c\u0430\u0448\u0438\u043d\u044b'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Car', verbose_name='\u041c\u0430\u0448\u0438\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Detail', verbose_name='\u041d\u043e\u043c\u0435\u043d\u043a\u043b\u0430\u0442\u0443\u0440\u0430 \u0434\u0435\u0442\u0430\u043b\u0438'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.OfficialDealer', verbose_name='\u0414\u0438\u043b\u0435\u0440'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='details',
            field=models.ManyToManyField(to='journal.Detail', verbose_name='\u0414\u0435\u0442\u0430\u043b\u0438'),
        ),
    ]
